### PR TITLE
mime/quotedprintable: support reading malformed (lower case) escaped chars.

### PR DESCRIPTION
**Pull request by kardianos**
Some broken tools generate invalid escape chars that use lower case characters. Support reading the invalid characters.

### CODE REVIEW

**Comment by alexcesaro** [comment]
Thanks! Do you have any idea which tools generate malformed escape chars?

**Comment by kardianos** [comment]
Nope. Got the malformed email from a client. Appears to have been generated
by a marketing campaign emailer.

**Comment by kardianos** [comment]
Hi Alex, Could you run this on your XP box and see if it works? On my VM it
is returning ~450. Not sure if it is the product of the OS time resolution
or the VM.

package main

import (
"fmt"
"os"
"runtime"
"sync"
"time"
)

const (
skipThreasholdMilli = 100
T                   = 8
timeoutMilli        = 100
)

func main() {
if skip() {
fmt.Println("SKIP PPROF")
os.Exit(1)
}
}

func skip() bool {
done := make(chan struct{})
time.AfterFunc(time.Millisecond*timeoutMilli, func() {
close(done)
})
wg := &sync.WaitGroup{}
result := make(chan int, T)
for range [T]struct{}{} {
wg.Add(1)
go func() {
defer wg.Done()
result <- thrash(done)
}()
}
wg.Wait()
close(result)
for diff := range result {
if diff > skipThreasholdMilli {
fmt.Println(diff)
return true
}
}
return false
}

func nextDiffMilli() int {
last := time.Now().UnixNano()
for {
next := time.Now().UnixNano()
if last != next {
return int((next - last) / (1000 * 1000))
}
}
}

func thrash(done chan struct{}) int {
runtime.LockOSThread()
defer runtime.UnlockOSThread()

diff := 0
for {
select {
case <-done:
return diff
default:
diff = nextDiffMilli()
if diff > skipThreasholdMilli {
return diff
}
}
}
return diff
}

**Comment by alexcesaro** [comment]
What is the link with quotedprintable? You should ask this question on golang-nuts or StackOverflow.

**Comment by kardianos** [comment]
Oh my word, email client totally pulled up the wrong email address, so sorry!

**Comment by alexcesaro** [comment]
No problem :)

**Pull request closed without merging**
